# Use official lightweight Java 17 runtime image
FROM eclipse-temurin:17-jre

# Set working directory inside the container
WORKDIR /app

# Copy the built JAR file from target folder into container
COPY target/*.jar app.jar

# Expose port 8080 (Spring Boot default)
EXPOSE 8080

# Command to run the Spring Boot application
ENTRYPOINT ["java", "-jar", "app.jar"]

#mvn clear package
#docker build -t pokeapi-app .
#docker run -p 8080:8080 pokeapi-app
