FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY target/pokeapi-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
#mvn clear package
#docker build -t pokeapi-app .
#docker run -p 8080:8080 pokeapi-app
